#!/bin/bash

SUM_FILE=/tmp/cron-checker.cron-tab.sum

md5sum -c --status $SUM_FILE 2> /dev/null
if [ $? == 1 ]
then
	echo "/etc/crontab has been modified" | mailx -s "/etc/crontab modified" root
	md5sum "/etc/crontab" > $SUM_FILE
fi
